name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - pip=20.3.3
  - mlflow=2.4.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - plotly==4.4.1
  - pillow=8.1.2
  - protobuf==3.20.*
  - pip:
      - wandb == 0.13.2
      
      - omegaconf==2.0.6





